/// <reference types="vitest/config" />
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'favicon-48.png', 'apple-touch-icon.png'],
      // SPEC-016 Notifications: generateSW's autogenerated worker has no push/notificationclick
      // handlers — real push requires our own service worker source.
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        // sw.ts imports workbox-precaching directly — nothing else to inject here.
        globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
      },
      devOptions: {
        enabled: true,
        type: 'module',
      },
      manifest: {
        name: 'Lugarcito',
        short_name: 'Lugarcito',
        description: 'Lugarcito no muestra listas. Ayuda a decidir.',
        theme_color: '#EF5A22',
        background_color: '#FCFBF8',
        display: 'standalone',
        start_url: '/',
        // Real Lugarcito icon: the BrainMark sparkle on the caju gradient, same glyph used
        // throughout the app. Drawn with a safe-zone margin so one PNG covers both purposes —
        // 'any' (drawn as-is) and 'maskable' (OS applies its own shape, glyph stays inside the crop).
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
        ],
        // SPEC-004 "Share Sheet (Principal)": registers Lugarcito as a native OS share target
        // (Instagram → Compartir → Lugarcito). GET-based so it's a plain navigation the SPA
        // router can handle — no service worker POST handling needed for text/url shares.
        share_target: {
          action: '/share',
          method: 'GET',
          params: {
            title: 'title',
            text: 'text',
            url: 'url',
          },
        },
      },
    }),
  ],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/test/setup.ts',
  },
});
