/// <reference types="vitest/config" />
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg'],
      // SPEC-016 Notifications: generateSW's autogenerated worker has no push/notificationclick
      // handlers — real push requires our own service worker source.
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        // sw.ts imports workbox-precaching directly — nothing else to inject here.
        globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
      },
      devOptions: {
        enabled: true,
        type: 'module',
      },
      manifest: {
        name: 'CajuEat',
        short_name: 'CajuEat',
        description: 'CajuEat no muestra listas. Ayuda a decidir.',
        theme_color: '#EF5A22',
        background_color: '#FCFBF8',
        display: 'standalone',
        start_url: '/',
        // TODO: replace with real maskable/any icon set (192/512 png)
        // generated from the Wordmark/BrainMark once the brand assets exist.
        icons: [],
      },
    }),
  ],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/test/setup.ts',
  },
});
